language: go

go:
  - 1.10.x
  - 1.11.x

sudo: false

env:
  - DEP_VERSION="0.5.0"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure -no-vendor -dry-run
  - dep ensure

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
 
script:
  - diff <(echo -n) <(gofmt -l $(find -name "*.go" | grep -v /vendor))
  - gometalinter ./... --vendor --deadline 100s
  - go test ./... -v
